export const START_GET_POPULAR_MOVIES: string = 'START_GET_POPULAR_MOVIES';
export const SUCCESS_GET_POPULAR_MOVIES: string = 'SUCCESS_GET_POPULAR_MOVIES';
export const ERROR_GET_POPULAR_MOVIES: string = 'ERROR_GET_POPULAR_MOVIES';

export const START_SEARCH_MOVIE: string = 'START_SEARCH_MOVIE';
export const SUCCESS_SEARCH_MOVIE: string = 'SUCCESS_SEARCH_MOVIE';
export const ERROR_SEARCH_MOVIE: string = 'ERROR_SEARCH_MOVIE';

export const START_GET_MOVIE_BY_ID: string = 'START_GET_MOVIE_BY_ID';
export const SUCCESS_GET_MOVIE_BY_ID: string = 'SUCCESS_GET_MOVIE_BY_ID';
export const ERROR_GET_MOVIE_BY_ID: string = 'ERROR_GET_MOVIE_BY_ID';